### PR TITLE
move out parsers

### PR DESCRIPTION
**Pull request by vestacic**
- Updated parsers to satisfy the `state+EitherT` monad requirement
- Moved out parsers to a separate file to increase code readability
- Cleaned up a little bit and reduced redundant functions for parsing
-  Fixed `parseUpdateStatement `and `parseDeleteStatement `as where condition is not necessary for these types of statements
- Got some questions about parsing the mentioned statements as in `where `clause it is not really possible to compare two columns and the  constant value must always be in the right side of the expression, is this intended?

### CODE REVIEW

**Comment by AkvileR** [comment]
I believe we chose a more simplified version for the update statement and didn't implement all the capabilities. I'm not sure what you meant by removing where conditions for update and delete statements though, where in the code did you implement that fix?

**Comment by arminasbrazenas** [comment]
There seems to be a build error

**Comment by vestacic** [comment]
> There seems to be a build error

fixed

**Comment by vestacic** [comment]
> I believe we chose a more simplified version for the update statement and didn't implement all the capabilities. I'm not sure what you meant by removing where conditions for update and delete statements though, where in the code did you implement that fix?

as we talked, simplified the parseWhereClause' to be able to operate without where clause flag

**Review by arminasbrazenas — APPROVED** [review]

**Pull request merged**
